name: "Test GitHub Action"
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "test.json"
          json: '{"name":"jsdaniell", "password":"mypass"}'
      - name: assert-json-exists
        run: "./test-json.sh"
        